/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface XtConfig {
  appName: string;
  appDescription: string;
  styling: {
    theme: string;
    rounded: string;
    baseSize: string;
    gap: string;
    sectionGap: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
